version: '3.5'

services:
  milvus:
    image: milvusdb/milvus:v2.3.4
    container_name: milvus-standalone
    ports:
      - "19530:19530"  # Milvus gRPC
      - "9091:9091"    # Milvus RESTful API
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: always
    environment:
      - TZ=Asia/Singapore
    volumes:
      - milvus_data:/var/lib/milvus

volumes:
  milvus_data: